package com.servlet;

import java.io.IOException;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.dao.ProductDAO;
import com.model.Product;

/**
 * AddProductServlet.java
 * Servlet implementation class AddProductServlet
 * Handles requests to add a new product to the inventory.
 * It retrieves product details from the form, creates a Product object,
 * and uses ProductDAO to persist it in the database.
 */
@WebServlet("/AddProductServlet")
public class AddProductServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;
    private ProductDAO productDAO;

    public void init() {
        productDAO = new ProductDAO();
    }

    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        String productName = request.getParameter("productName");
        String category = request.getParameter("category");
        double price = Double.parseDouble(request.getParameter("price"));
        int quantity = Integer.parseInt(request.getParameter("quantity"));

        // ProductID is typically auto-generated by the database, so we don't set it here.
        // If your database doesn't auto-generate, you'd need a mechanism to generate unique IDs.
        Product newProduct = new Product(0, productName, category, price, quantity);

        boolean success = productDAO.addProduct(newProduct);

        if (success) {
            request.setAttribute("message", "Product added successfully!");
        } else {
            request.setAttribute("message", "Failed to add product. Please try again.");
        }
        // Forward to a confirmation page or back to the add product form with a message
        request.getRequestDispatcher("productadd.jsp").forward(request, response);
    }
}
